name: main_ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: self-hosted

    strategy:
      matrix:
        go-version: [1.18]

    steps:
      - uses: actions/checkout@v2

      - name: setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup project
        run: |
          docker-compose stop
          docker-compose up --build -d